// <auto-generated />
using System;
using ADUSAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADUSAPI.Migrations
{
    [DbContext(typeof(ADUSContext))]
    [Migration("20250409030257_loaduf")]
    partial class loaduf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADUSAPI.Entities.ADUSLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("datalog")
                        .HasColumnType("datetime2");

                    b.Property<string>("idconta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ADUSLogs");
                });

            modelBuilder.Entity("ADUSAPI.Entities.CotacaoMoeda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CotacaoData")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CotacaoValor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("IdMoeda")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMoeda");

                    b.ToTable("CotacoesMoeda", (string)null);
                });

            modelBuilder.Entity("ADUSAPI.Entities.Moeda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Moedas", (string)null);
                });

            modelBuilder.Entity("ADUSAPI.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIBGE")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("IdUF")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdUF");

                    b.ToTable("Municipios", (string)null);
                });

            modelBuilder.Entity("ADUSAPI.Entities.Parceiro", b =>
                {
                    b.Property<string>("uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Cidade")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("int");

                    b.Property<string>("Fantasia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdRepresentante")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Profissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Registro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexo")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<int>("TipodePessoa")
                        .HasColumnType("int");

                    b.Property<int>("UF")
                        .HasColumnType("int");

                    b.Property<DateTime?>("datains")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dataup")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("uid");

                    b.HasIndex("Cidade");

                    b.HasIndex("IdRepresentante");

                    b.HasIndex("UF");

                    b.ToTable("Parceiros", (string)null);
                });

            modelBuilder.Entity("ADUSAPI.Entities.UF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIBGE")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("UFs", (string)null);
                });

            modelBuilder.Entity("ADUSAPI.Entities.CotacaoMoeda", b =>
                {
                    b.HasOne("ADUSAPI.Entities.Moeda", "moeda")
                        .WithMany("cotacaoMoedas")
                        .HasForeignKey("IdMoeda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("moeda");
                });

            modelBuilder.Entity("ADUSAPI.Entities.Municipio", b =>
                {
                    b.HasOne("ADUSAPI.Entities.UF", "uF")
                        .WithMany("Municipios")
                        .HasForeignKey("IdUF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("uF");
                });

            modelBuilder.Entity("ADUSAPI.Entities.Parceiro", b =>
                {
                    b.HasOne("ADUSAPI.Entities.Municipio", "cidade")
                        .WithMany("parceiros")
                        .HasForeignKey("Cidade")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ADUSAPI.Entities.Parceiro", "Representante")
                        .WithMany("empresas")
                        .HasForeignKey("IdRepresentante")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ADUSAPI.Entities.UF", "uf")
                        .WithMany("Parceiros")
                        .HasForeignKey("UF")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Representante");

                    b.Navigation("cidade");

                    b.Navigation("uf");
                });

            modelBuilder.Entity("ADUSAPI.Entities.Moeda", b =>
                {
                    b.Navigation("cotacaoMoedas");
                });

            modelBuilder.Entity("ADUSAPI.Entities.Municipio", b =>
                {
                    b.Navigation("parceiros");
                });

            modelBuilder.Entity("ADUSAPI.Entities.Parceiro", b =>
                {
                    b.Navigation("empresas");
                });

            modelBuilder.Entity("ADUSAPI.Entities.UF", b =>
                {
                    b.Navigation("Municipios");

                    b.Navigation("Parceiros");
                });
#pragma warning restore 612, 618
        }
    }
}
